repos:
  - repo: local
    hooks:
      - id: sciaudit
        name: SciAudit
        entry: python -m sciaudit
        language: system
        types: [python]
        files: \.(py|ipynb)$
        pass_filenames: true
